### ISSUE TITLE
Add publisher prefixes to the JSON output

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/getdata#4]
This involves a change that the database end of the JSON output.

We think we want to add: e.g.

publisher_prefix: "360G-ABC"

somewhere.

**Comment by stevieflow** [comment]
I think this is a requirement for the GrantNav sprint - and work around provenance: https://github.com/OpenDataServices/grantnav/issues/137

@Bjwebb @robredpath

**Comment by caprenter** [comment]
This should now be done. There is a 'prefix' field available in the JSON output now.
See: http://threesixtygiving.github.io/getdata/ for documentation
