### ISSUE TITLE
Dataset needs a licence

### ISSUE THREAD

**Issue by BobHarper1** [ThreeSixtyGiving/getdata#7]
A licence for the `data.json` feed itself

Preferably an open licence ;)

**Comment by caprenter** [comment]
Thanks @BobHarper1 - this is an oversight on our part. Oops.
We'll get an open license on it in the next week.

Thanks for point it out to us.

Current thinking is:
Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
We will state this on the http://threesixtygiving.github.io/getdata/ documentation 
and see if we can add it to the data.json file as well.

**Comment by caprenter** [comment]
Sorry, this issue got forgotten.

We've looked at it again today and don't see the need to add the share alike part of the CC licence. So we're gonna go with CC-BY and I'll put a pull request in on this on Thursday.

**Comment by Bjwebb** [comment]
This has been done now https://threesixtygiving.github.io/getdata/#license
